### PR TITLE
Add star, transfer and person icon

### PR DESCRIPTION
**Pull request by ayumitk**
Added new icons

Screenshot 2023-10-03 at 3 05 35 PM

### CODE REVIEW

**Review by impelcrypto — CHANGES_REQUESTED** [review]
I think you need to export these files from 'packages/Icons/index.ts' to be able to use on other repos, no?

https://github.com/AstarNetwork/astar-ui/blob/main/packages/Icons/index.ts

**Comment by bobo-k2** [comment]
> I think you need to export these files from 'packages/Icons/index.ts' to be able to use on other repos, no?
> 
> https://github.com/AstarNetwork/astar-ui/blob/main/packages/Icons/index.ts

Yes

**Comment by ayumitk** [comment]
@impelcrypto @bobo-k2 I've updated the following files  ([0e9fd48](https://github.com/AstarNetwork/astar-ui/pull/84/commits/0e9fd48a7d1e53cdb39761f4b0beb781960dce01))
- packages/Icons/index.ts
- packages/export_type.ts

Could you please review the PR once again?

**Review by impelcrypto — APPROVED** [review]

**Comment by impelcrypto** [comment]
@ayumitk  Approved. You can merge this PR and try updating Astar UI library in our portal.

**Pull request merged**
